# version: '3.8'

# services:
#   db:
#     image: postgres:15
#     container_name: reload-postgres
#     restart: always
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: postgres
#       POSTGRES_DB: reload_db
#     ports:
#       - "5432:5432"
#     volumes:
#       - pg_data:/var/lib/postgresql/data

# volumes:
#   pg_data:
# version: "3.8"

services:
  db:
    image: postgres:15
    container_name: reloadext-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: reload_db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@reload.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
  # backend:
  #   build:
  #     context: .
  #     dockerfile: apps/backend/Dockerfile
  #   ports:
  #     - "3001:3001"
  #   env_file:
  #     - .env.docker

volumes:
  pg_data:
# networks:
#   backend:
# frontend:
#   build:
#     context: .
#     dockerfile: apps/frontend/Dockerfile
#   container_name: reload-frontend
#   depends_on:
#     - backend
#   ports:
#     - "3000:3000"
#   environment:
#     NEXT_PUBLIC_API_URL: http://localhost:3001
